### ISSUE TITLE
Document sign-out in README

### ISSUE THREAD

**Issue by objorke** [veracity/Veracity.Authentication.OpenIDConnect.Core#17]
On signout, the application should redirect to `https://www.veracity.com/auth/logout`
Add a section in the README.md that describes this.

**Comment by mingderekwang** [comment]
Hello, for the application which has backed(server), it may make sense now, but we are in the process migrate all the app from ADFS to B2C and we already have the deadline for that, after we finish this part, redirect to this endpoint will be meaningless and we do not want Home to have this responsibility.  So this will not put as the standard requirement for apps.
