### ISSUE TITLE
Split VeracityIntegrationOptions

### ISSUE THREAD

**Issue by objorke** [veracity/Veracity.Authentication.OpenIDConnect.Core#2]
This class currently has two concerns:
- settings for OpenIdConnectOptions
- settings for VeracityPlatformService

**Comment by mingderekwang** [comment]
Veracity is not a standalone identity provider, most services hosted in platform need to consumer the services or different APIs, according to current feedback we have, put Veracity config as a section is best for services integrate, but we will continuously collect feedback about this, if you think this is a strong needs, please vote for this issue.
