### ISSUE TITLE
Provide default values in VeracityIntegrationOptions

### ISSUE THREAD

**Issue by objorke** [veracity/Veracity.Authentication.OpenIDConnect.Core#5]
```cs
Tenant = "dnvglb2cprod.onmicrosoft.com"
SignUpSignInPolicyId = "B2C_1A_SignInWithADFSIdp"
RedirectUri = "https://localhost:3000/signin-oidc"
```

**Comment by mingderekwang** [comment]
Developer will get those value in developer.veracity.com and emails, the policy may change in future. 3000 port is not default enabled for operation system, we want the developer to choose the setting.
